"""G3-B paper model contract (PAPER_MODEL_V1).

Frozen by results/package_baseline/g3_model_contract/paper_model_contract.json
(generated by scripts/g3_model_contract.py). The model is a verbatim port of
IndigoFloyd/SoybeanWebsite AlexNet_206.py; the source commit is recorded in
the JSON.

Run:  python tests/test_paper_model_contract.py   (or pytest; CPU is enough)
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)
sys.path.insert(0, os.path.join(ROOT, 'src'))

import torch
import torch.nn.functional as F

from paper_model.soydngp_ca import AlexNet, CA_Block

CONTRACT = os.path.join(ROOT, 'results', 'package_baseline', 'g3_model_contract',
                       'paper_model_contract.json')
B = 2


def _load():
    assert os.path.exists(CONTRACT), 'run scripts/g3_model_contract.py first'
    with open(CONTRACT) as f:
        return json.load(f)


def _shapes(module):
    shapes = {}
    handles = []
    for name, child in module.named_children():
        def h(m, inp, out, name=name):
            shapes[name] = list(out.shape)
        handles.append(child.register_forward_hook(h))
    with torch.no_grad():
        module(torch.randn(B, 3, 206, 206))
    for h in handles:
        h.remove()
    return shapes


def test_source_commit_recorded():
    c = _load()
    assert c['source']['commit']
    assert c['source']['file'] == 'AlexNet_206.py'
    assert c['source']['repo'] == 'IndigoFloyd/SoybeanWebsite'


def test_regression_forward():
    c = _load()
    m = AlexNet()
    m.net.eval()
    with torch.no_grad():
        out = m.net(torch.randn(B, 3, 206, 206))
    assert out.shape == tuple(c['regression']['output_shape']) == (B, 1)
    assert bool(torch.isfinite(out).all())


def test_backward_and_grads():
    m = AlexNet()
    m.net.train()
    out = m.net(torch.randn(B, 3, 206, 206))
    F.mse_loss(out, torch.rand_like(out)).backward()
    assert all(bool(torch.isfinite(p.grad).all()) for p in m.parameters() if p.grad is not None)


def test_architecture_freeze():
    c = _load()
    m = AlexNet()
    convs = [i for i, mod in enumerate(m.net) if isinstance(mod, torch.nn.Conv2d)]
    cas = [i for i, mod in enumerate(m.net) if isinstance(mod, CA_Block)]
    assert len(convs) == c['architecture']['conv_layers'] == 12
    assert cas == [ca['index'] for ca in c['architecture']['ca_blocks']]
    flat = next(mod for mod in m.net if isinstance(mod, torch.nn.Flatten))
    out = {}

    def h(mod, inp, o):
        out['shape'] = list(o.shape)

    handle = flat.register_forward_hook(h)
    with torch.no_grad():
        m.net(torch.randn(B, 3, 206, 206))
    handle.remove()
    assert out['shape'][1] == c['architecture']['flatten_features'] == 50176


def test_intermediate_shapes_match_contract():
    c = _load()
    m = AlexNet()
    m.net.eval()
    assert _shapes(m.net) == c['intermediate_shapes']


def test_parameter_counts_match_contract():
    c = _load()
    m = AlexNet()
    total = sum(p.numel() for p in m.parameters())
    trainable = sum(p.numel() for p in m.parameters() if p.requires_grad)
    assert total == c['total_parameters']
    assert trainable == c['trainable_parameters']
    assert sorted(m.state_dict().keys()) == c['state_dict_keys']


if __name__ == '__main__':
    fns = [v for k, v in sorted(globals().items())
           if k.startswith('test_') and callable(v)]
    for fn in fns:
        fn()
        print('PASS', fn.__name__)
    print('all paper model contract tests passed')
