"""G3-A package model contract.

Frozen by results/package_baseline/g3_model_contract/package_model_contract.json
(generated by scripts/g3_model_contract.py). Regenerate the JSON only when the
model code or model.yaml intentionally changes.

Run:  python tests/test_package_model_contract.py   (or pytest; CPU is enough)
"""
import json
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import torch
import torch.nn.functional as F

from soydngpnext.remodel import remodel

CONTRACT = os.path.join(ROOT, 'results', 'package_baseline', 'g3_model_contract',
                       'package_model_contract.json')
YAML = os.path.join(ROOT, 'soydngpnext', 'data', 'model.yaml')
B = 2


def _load():
    assert os.path.exists(CONTRACT), 'run scripts/g3_model_contract.py first'
    with open(CONTRACT) as f:
        return json.load(f)


def _shapes(net):
    shapes = {}
    handles = []
    for name, child in net.named_children():
        def h(m, inp, out, name=name):
            shapes[name] = list(out.shape)
        handles.append(child.register_forward_hook(h))
    with torch.no_grad():
        net(torch.randn(B, 3, 206, 206))
    for h in handles:
        h.remove()
    return shapes


def _flatten_features(net):
    flat = next(m for m in net.modules() if isinstance(m, torch.nn.Flatten))
    out = {}

    def h(m, inp, o):
        out['shape'] = list(o.shape)

    handle = flat.register_forward_hook(h)
    with torch.no_grad():
        net(torch.randn(B, 3, 206, 206))
    handle.remove()
    return out['shape'][1]


def test_regression_forward():
    c = _load()
    net, _ = remodel(YAML, 1, show_structure=False)
    net.eval()
    with torch.no_grad():
        out = net(torch.randn(B, 3, 206, 206))
    assert out.shape == tuple(c['regression']['output_shape']) == (B, 1)
    assert bool(torch.isfinite(out).all())


def test_classification_forward():
    c = _load()
    net, _ = remodel(YAML, 9, show_structure=False)
    net.eval()
    with torch.no_grad():
        out = net(torch.randn(B, 3, 206, 206))
    assert out.shape == tuple(c['classification']['output_shape']) == (B, 9)
    assert bool(torch.isfinite(out).all())


def test_backward_and_grads():
    x = torch.randn(B, 3, 206, 206)
    net, _ = remodel(YAML, 1, show_structure=False)
    net.train()
    out = net(x)
    F.mse_loss(out, torch.rand_like(out)).backward()
    assert all(bool(torch.isfinite(p.grad).all()) for p in net.parameters() if p.grad is not None)

    net_c, _ = remodel(YAML, 9, show_structure=False)
    net_c.train()
    out_c = net_c(x)
    F.cross_entropy(out_c, torch.randint(0, 9, (B,))).backward()
    assert all(bool(torch.isfinite(p.grad).all()) for p in net_c.parameters() if p.grad is not None)


def test_intermediate_shapes_match_contract():
    c = _load()
    net, _ = remodel(YAML, 1, show_structure=False)
    net.eval()
    assert _shapes(net) == c['intermediate_shapes']


def test_flatten_features_checksum():
    c = _load()
    net, _ = remodel(YAML, 1, show_structure=False)
    assert _flatten_features(net) == c['flatten_features'] == 50176


def test_parameter_counts_match_contract():
    c = _load()
    net, _ = remodel(YAML, 1, show_structure=False)
    total = sum(p.numel() for p in net.parameters())
    trainable = sum(p.numel() for p in net.parameters() if p.requires_grad)
    assert total == c['total_parameters']
    assert trainable == c['trainable_parameters']
    assert sorted(net.state_dict().keys()) == c['state_dict_keys']
    assert [[n, type(ch).__name__] for n, ch in net.named_children()] == c['module_names']


if __name__ == '__main__':
    fns = [v for k, v in sorted(globals().items())
           if k.startswith('test_') and callable(v)]
    for fn in fns:
        fn()
        print('PASS', fn.__name__)
    print('all package model contract tests passed')
